name: build

on:
  push:
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta-environment
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/rust-environment          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64          
          push: true
          tags: ${{ steps.meta-environment.outputs.tags }}
          labels: ${{ steps.meta-environment.outputs.labels }}
